<?php
    if(isset($_SESSION['logged']) && $_SESSION['logged'] === 'LOGGED'){
        header('Location: /dashboard');
    }
?>


<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="referrer" content="strict-origin-when-cross-origin">
        <title>W-Tech SI</title>
        <link rel="stylesheet" href="./css-bootstrap/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="./fontawesome/css/all.min.css">
        <link rel="shortcut icon" href="./img/coins-solid.svg" type="image/x-icon">
        <link rel="stylesheet" href="./css/style.css">
        <link rel="stylesheet" href="./css/css-sidebar.css">
        <link rel="stylesheet" href="./css/css-cards.css">
        <link rel="stylesheet" href="./css/css-menu.css">
        <link rel="stylesheet" href="./css/css-checkbox.css">
        <link rel="stylesheet" href="./css/modal.css">
        <link rel="stylesheet" href="./css/receita.css">
        <link rel="stylesheet" href="./css/despesa.css">
        <link rel="stylesheet" href="./css/seletores.css">
        <link rel="stylesheet" href="./css/mes.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Maven+Pro:wght@400;500&display=swap" rel="stylesheet">
        <script src="https://accounts.google.com/gsi/client" async defer></script>
        <style>

            body, html{
                background-color: rgb(247, 247, 247);
                margin: 0;
                padding: 0;
                width: 100%;
                height: 100%;
            }
        </style>
    </head>
    <body>
        <div class="box-index">
            <div class="box-content">
                <div class="brand">
                    <img src="./img/img.png" alt="" width="100">
                </div>
                <div class="title">
                    Login
                </div>

                <div class="box-body">
                    
                    <form action="/validateUser" method="POST">
                        <div>
                            <label for="user">Username / E-mail</label>
                            <div>
                                <input class="form-control" type="text" name="user" id="user">
                            </div>
                        </div>

                        <div class="mt-3">
                            <label for="pass">Senha</label>
                            <div>
                                <input class="form-control" type="password" name="pass" id="pass">
                            </div>
                        </div>

                        <?php if(isset($_REQUEST['login']) && $_REQUEST['login'] === 'Error'){ ?>

                            <div class="mt-3 text-center">
                                <span class="text-danger">Usúario ou Senha inválido, tente novamente.</span>
                            </div>

                        <?php } ?>

                        <div>
                            <button class="btn-login" type="submit">Entrar</button>
                        </div>
                    </form>

                    <div id="g_id_onload"
                        data-client_id="614610442680-mmot2uo15l8vfie0i0g6slq5990b7rv7.apps.googleusercontent.com"
                        data-context="signup"
                        data-ux_mode="popup"
                        data-callback="handleCredentialResponse"
                        data-auto_prompt="false">
                    </div>

                    <div class="g_id_signin mt-2"
                        data-type="standard"
                        data-shape="pill"
                        data-theme="outline"
                        data-text="continue_with"
                        data-size="medium"
                        data-logo_alignment="center"
                        data-width="350">
                    </div>
                </div>
            </div>
        </div>
    </body>

    <script>
      window.onload = function () {
        google.accounts.id.initialize({
          client_id: '614610442680-mmot2uo15l8vfie0i0g6slq5990b7rv7.apps.googleusercontent.com',
          callback: handleCredentialResponse,
          ux_mode: "redirect"
        });
      };

      function handleCredentialResponse(response){

        

        const responsePayload = decodeJwtResponse(response.credential)

        console.log("ID: " + responsePayload.sub);
        console.log('Full Name: ' + responsePayload.name);
        console.log('Given Name: ' + responsePayload.given_name);
        console.log('Family Name: ' + responsePayload.family_name);
        console.log("Image URL: " + responsePayload.picture);
        console.log("Email: " + responsePayload.email);

        window.location.href=`https://controledegastos.com/loginGoogle?fullName=${responsePayload.name}&givenName=${responsePayload.given_name}&familyName=${responsePayload.family_name}&image=${responsePayload.picture}&email=${responsePayload.email}`
      }

      function decodeJwtResponse (token) {
        let base64Url = token.split('.')[1];
        let base64 = base64Url.replace(/-/g, '+').replace(/_/g, '/');
        let jsonPayload = decodeURIComponent(atob(base64).split('').map(function(c) {
            return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
        }).join(''));

        return JSON.parse(jsonPayload);
      }
    </script>
</html>