<?php
    if(!(isset($_SESSION['logged']) && $_SESSION['logged'] === 'LOGGED')){
        header('Location: /?session=timeOut');
    }
?>
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="./css-bootstrap/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="./fontawesome/css/all.min.css">
        <link rel="shortcut icon" href="./img/coins-solid.svg" type="image/x-icon">
        <link rel="stylesheet" href="./css/style.css">
        <link rel="stylesheet" href="./css/css-sidebar.css">
        <link rel="stylesheet" href="./css/css-cards.css">
        <link rel="stylesheet" href="./css/css-menu.css">
        <link rel="stylesheet" href="./css/css-checkbox.css">
        <link rel="stylesheet" href="./css/modal.css">
        <link rel="stylesheet" href="./css/seletores.css">
        <link rel="stylesheet" href="./css/mes.css">
        <link rel="stylesheet" href="./css/receita.css">
        <link rel="stylesheet" href="./css/despesa.css">
        <link rel="stylesheet" href="./css/media-query.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Maven+Pro:wght@400;500&display=swap" rel="stylesheet"> 
        <title>Dashboard</title>

        <style>
            
        </style>
    </head>

    <body>
        <!-- modal receitas -->
        <div id="modal-receita" class="modal d-none">
            <div class="modal-body">
                <div class="modal-content modal-receita">
                    <div class="mh">
                        <h4 class="d-inline">Nova Receita</h4>
                        <span id="fechar" class="close fa-regular fa-x" onclick="fechar('modal-receita')"></span>
                    </div>

                    <form action="/novaReceita">
                        <!-- valor -->
                        <div class="input-group">
                            <i class="fa-solid fa-calculator"></i>
                            <input type="text" name="valor" id="valor-receita" class="form-control" placeholder="R$">
                        </div>

                        <!-- rent paga -->
                        <div>
                            <div class="row d-flex receita-check">
                                <div class="col-6 align-self-end">
                                    <i class="fa-regular fa-circle-check check-icon"></i>
                                    <label id="text-switch-receita" for="switch-receita" class="text-switch">Liquidado</label>
                                </div>
                                <div class="col-6 d-flex justify-content-end">
                                    <input type="checkbox" id="switch-receita" class="checkbox" value="liquidado" name="isPaid" checked=true>
                                    <label for="switch-receita" class="toggle"></label>
                                </div>
                            </div>
                        </div>

                        <!-- data -->
                        <div class="mt-4 input-group">
                            <i class="fa-solid fa-calendar-days"></i>
                            <input id="dt-receita" type="date" name="data" class="form-control">
                        </div>

                        <!-- pagador -->
                        <div class="mt-4 input-group">
                            <i class="fa-solid fa-receipt"></i>
                            <input type="text" name="payer" id="pagador-receita" class="form-control" placeholder="Pagador">
                        </div>

                        <!-- categoria -->
                        <div class="select-categoria-receita mt-4">

                            <div class="container-box">

                                <div id="categoria-receita" class="container-options">

                                    <div class="option r">
                                        <input type="radio" name="categoria" class="radio" id="venda-mercadoria" value="venda-mercadoria">
                                        <label for="venda-mercadoria">Venda de Mercadoria</label>
                                    </div>

                                    <div class="option r">
                                        <input type="radio" name="categoria" class="radio" id="servico" value="serviço">
                                        <label for="servico">Serviço</label>
                                    </div>

                                    <div class="option r">
                                        <input type="radio" name="categoria" class="radio" id="caixa" value="caixa">
                                        <label for="caixa">Caixa</label>
                                    </div>

                                    <div class="option r">
                                        <input type="radio" name="categoria" class="radio" id="matriz" value="matriz">
                                        <label for="matriz">Matriz</label>
                                    </div>
                                </div>
                                <div id="cat-selector-receita" class="selected-option">
                                    <i class="fa-solid fa-flag"></i>
                                    <span id="text-receita">Categorias</span>
                                </div>
                            </div>
                        </div>

                        <!-- carteira -->
                        <div class="div-carteira-receita mt-4">
                            <div class="container-box">
                                <div id="carteira-receita" class="container-options">
                                    <div class="option w">
                                        <input type="radio" name="carteira-receita" id="empresa-receita" class="radio" value="empresa">
                                        <label for="empresa-receita">Empresa</label>
                                    </div>

                                    <div class="option w">
                                        <input type="radio" name="carteira-receita" id="pessoal-receita" class="radio" value="pessoal">
                                        <label for="pessoal-receita">Pessoal</label>
                                    </div>
                                </div>

                                <div id="wallet-selector-receita" class="selected-option">
                                    <i class="fa-solid fa-building-columns"></i>
                                    <span id="wallet-text">Carteira</span>
                                </div>
                            </div>
                        </div>

                        <!-- botão submit -->
                        <div class="submit receita mt-4">
                            <button type="submit">Salvar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- modal despesa-->
        <div id="modal" class="modal d-none">
            <div class="modal-body">
                <div class="modal-content modal-despesa">
                    <div class="mh">
                        <h4>Nova Despesa</h4>
                        <span class="close fa-regular fa-x" onclick="fechar('modal')"></span>
                    </div>
                    <form action="/novaDespesa">
                        <!-- valor -->
                        <div class="input-group">
                            <i class="fa-solid fa-calculator"></i>
                            <input type="text" name="valor" id="valor" class="form-control despesa-valor" placeholder="R$">
                        </div>

                        <!-- despesa paga -->
                        <div>
                            <div class="row d-flex">
                                <div class="col-6 align-self-end">
                                    <i class="fa-regular fa-circle-check check-icon"></i>
                                    <label id="text-switch" for="switch" class="text-switch">Foi Paga</label>
                                </div>
                                <div class="col-6 d-flex justify-content-end">
                                    <input type="checkbox" id="switch" class="checkbox" value="pago" name="isPaid" checked=true>                        
                                    <label for="switch" class="toggle"></label>
                                </div>
                            </div>
                        </div>

                        <!-- data -->
                        <div class="mt-4 input-group">
                            <i class="fa-solid fa-calendar-days"></i>
                            <input id="dt" type="date" name="data" class="form-control"> 
                        </div>

                        <!-- beneficiario -->
                        <div class="mt-4 input-group">
                            <i class="fa-solid fa-receipt"></i>
                            <input type="text" name="bene" id="bene" class="form-control" placeholder="Beneficiário">
                        </div>

                        <!-- categoria -->
                        <div class="select-categoria mt-4">
                
                            <div class="container-box">

                                <div id="categoria" class="container-options">

                                    <div class="option waD">
                                        <input type="radio" name="categoria" class="radio" id="compra-mercadoria" value="compra-mercadoria">
                                        <label for="compra-mercadoria">Compra de Mercadoria</label>
                                    </div>

                                    <div class="option waD">
                                        <input type="radio" name="categoria" class="radio" id="conta" value="conta">
                                        <label for="conta">Contas</label>
                                    </div>

                                    <div class="option waD">
                                        <input type="radio" name="categoria" class="radio" id="imposto" value="imposto">
                                        <label for="imposto">Impostos</label>
                                    </div>

                                    <div class="option waD">
                                        <input type="radio" name="categoria" class="radio" id="emprestimo" value="empréstimo">
                                        <label for="emprestimo">Empréstimo</label>
                                    </div>

                                    <div class="option waD">
                                        <input type="radio" name="categoria" class="radio" id="alimentacao" value="alimentacao">
                                        <label for="alimentacao">Alimentação</label>
                                    </div>

                                    <div class="option waD">
                                        <input type="radio" name="categoria" class="radio" id="transporte" value="transporte">
                                        <label for="transporte">Transporte</label>
                                    </div>
                                    <div class="option waD">
                                        <input type="radio" name="categoria" class="radio" id="outros" value="outros">
                                        <label for="outros">Outros</label>
                                    </div>                                
                                </div> 
                                <div id="categoria-select" class="selected-option ">
                                    <i class="fa-solid fa-flag"></i>
                                    <span id="cat-text">Categorias</span>
                                </div>
                                
                            </div>  
                        </div>
                        
                        <!-- carteira -->
                        <div class="div-carteira mt-4">
                            <div class="container-box">
                                <div id="carteira" class="container-options" >
                                    <div class="option wd">
                                        <input type="radio" name="carteira" id="empresa" class="radio" value="empresa">
                                        <label for="empresa">Empresa</label>
                                    </div>

                                    <div class="option wd">
                                        <input type="radio" name="carteira" id="pessoal" class="radio" value="pessoal">
                                        <label for="pessoal">Pessoal</label>
                                    </div>
                                </div>

                                <div id="wdSelector" class="selected-option">
                                    <i class="fa-solid fa-building-columns"></i>
                                    <span id="wdText">Carteira</span>
                                </div>
                            </div>
                        </div>

                        <!-- botão submit -->
                        <div class="submit mt-4">
                            <button type="submit">Salvar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        
        <!-- barra lateral -->
        <div id="sidebar">
            <div class="sibebar-logo">
                <img src="./img/img.png" width="80" alt="">
                <ul class="navbar-menu d-none">
                    <li><a href="">Dashboard</a></li>
                    <li><a href="">Novo</a></li>
                    <li><a href="">Transações</a></li>
                </ul>
            </div>

            <div class="sidebar-btn-add">
                <div id="btn-add">
                    <button id="btn" class="btn-sidebar">
                        <i id="btn-icon" class="fa-solid fa-plus"></i>
                    </button>

                    <ul id="menu" class="d-none">
                        <li>
                            <a onclick="modal('modal')" class="cl">
                                <i class="fa-solid fa-arrow-trend-down dp"></i>
                                Despesa
                            </a>
                        </li>
                        <li>
                            <a onclick="modal('modal-receita')" class="cl">
                                <i class="fa-solid fa-arrow-trend-up rt"></i>
                                Receita
                            </a>
                        </li>
                        <li><a href="">
                            <i class="fa-solid fa-bag-shopping vd"></i>
                            Venda
                        </a></li>
                    </ul>
                </div>
            </div>

            <div class="sidebar-menu">
                <ul>
                    <li class="margin-t active">
                        <a href="#"><img src="./img/home.png" width="35" alt=""></a>
                    </li>
                    <li class="margin-t">
                        <a href="#"><img src="./img/lista.png" width="33" alt=""></i></a>

                    </li><li class="margin-t">
                        <a href="/logout"><img src="./img/img-exit.png" width="20" alt=""></i></i></a>
                    </li>
                </ul>

            </div>
        </div>
        
        <!-- conteudo principal -->
        <div id="content" class="content">

        

            <!-- pop-up success_Error -->
            <?php if(isset($_REQUEST['register']) && $_REQUEST['register'] == 'despesaRegisterSuccess' || isset($_REQUEST['register']) && $_REQUEST['register'] == 'receitaRegisterSuccess'){ ?>
                <div id="register" class="expense-success">
                    <span class="expense-content"><i class="fa-regular fa-circle-check"></i></span>
                    <span class="expense-content fs-3 px-2">|</span>
                    <span class="expense-content"><span class="text-capitalize"><?= str_replace('RegisterSuccess', '', $_REQUEST['register']) ?></span> criada com sucesso.</span>
                </div>
            <?php } ?>

            <?php if(isset($_REQUEST['register']) && $_REQUEST['register'] == 'despesaRegisterError' || isset($_REQUEST['register']) && $_REQUEST['register'] == 'receitaRegisterError'){ ?>
                <div id="register" class="expense-error">
                    <span class="expense-content"><i class="fa-regular fa-circle-check"></i></span>
                    <span class="expense-content fs-3 px-2">|</span>
                    <span class="expense-content">Erro ao criar <?= str_replace('RegisterError', '', $_REQUEST['register']) ?>, verifique os dados e tente novamente.</span>
                </div>
            <?php } ?>

            <div>
                <div class="topo">
                    <div style="align-self: center;">
                        <div class="select-content">
                            <div class="select-box">

                                <div class="options-container">

                                    <div class="option">
                                        <input type="radio" class="radio" name="mes" id="jan" value="01">
                                        <label for="jan">Jan</label>
                                    </div>

                                    <div class="option">
                                        <input type="radio" class="radio" name="mes" id="fev" value="02">
                                        <label for="fev">Fev</label>
                                    </div>

                                    <div class="option">
                                        <input type="radio" class="radio" name="mes" id="mar" value="03">
                                        <label for="mar">Mar</label>
                                    </div>

                                    <div class="option">
                                        <input type="radio" class="radio" name="mes" id="abr" value="04">
                                        <label for="abr">Abr</label>
                                    </div>

                                    <div class="option">
                                        <input type="radio" class="radio" name="mes" id="mai" value="05">
                                        <label for="mai">Mai</label>
                                    </div>

                                    <div class="option">
                                        <input type="radio" class="radio" name="mes" id="jun" value="06">
                                        <label for="jun">Jun</label>
                                    </div>

                                    <div class="option">
                                        <input type="radio" class="radio" name="mes" id="jul" value="07">
                                        <label for="jul">Jul</label>
                                    </div>

                                    <div class="option">
                                        <input type="radio" class="radio" name="mes" id="ago" value="08">
                                        <label for="ago">Ago</label>
                                    </div>

                                    <div class="option">
                                        <input type="radio" class="radio" name="mes" id="set" value="09">
                                        <label for="set">Set</label>
                                    </div>

                                    <div class="option">
                                        <input type="radio" class="radio" name="mes" id="out" value="10">
                                        <label for="out">Out</label>
                                    </div>

                                    <div class="option">
                                        <input type="radio" class="radio" name="mes" id="nov" value="11">
                                        <label for="nov">Nov</label>
                                    </div>

                                    <div class="option">
                                        <input type="radio" class="radio" name="mes" id="dez" value="12">
                                        <label for="dez">Dez</label>
                                    </div>
                                </div>

                                <div id="selectMonth" class="selected">
                                    <span id="mes">Mês</span>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div id="usuario">
                        <span class="user"><img class="user-image" src="<?= isset($_SESSION['image']) ? $_SESSION['image'] : ''?>" alt=""></i></span>
                        <span class="user-name"><?= isset($_SESSION['user']) ? $_SESSION['user'] : '' ?></span>
                        <span class="angle"><i class="fa-solid fa-angle-down"></i></span>
                    </div>
                </div>
            </div>

            <div>
                <div class="titulo">
                    <h3>Dashboard</h3>
                </div>
            </div>
            
            <div class="linha">
                <!-- saldo -->
              <a href="" id="saldo-atual" class="cartao">
                  <span class="text-card">Saldo atual<img src="./img/angle.png" width="25" alt=""></span>
                  <div class="icone-circle c-saldo">
                      <span class="icone saldo"><i class="fa-solid fa-building-columns"></i></span>
                  </div>
                  <h4 id="saldo" style="color: #2196F3;"></h4>
              </a>
            
              <!-- receita -->
              <a href="/receitas" class="cartao">
                <span class="text-card">Receitas<img src="./img/angle.png" width="25" alt=""></span>
                <div class="icone-circle c-receita">
                    <span class="icone receita"><i class="fa-solid fa-arrow-up"></i></span>
                </div>
                <h4 id="rent" class="text-success"></h4>
              </a>

              <!-- despesas -->
              <a href="/despesa" class="cartao">
                <span class="text-card">Despesas<img src="./img/angle.png" width="25" alt=""></span>
                <div class="icone-circle c-despesa">
                    <span class="icone despesa"><i class="fa-solid fa-arrow-down"></i></span>
                </div>
                <h4 id="expense" class="text-danger"></h4>
              </a>

              <!-- vendas -->
              <a href="" class="cartao">
                <span class="text-card">Vendas<img src="./img/angle.png" width="25" alt=""></span>
                <div class="icone-circle c-vendas">
                    <span class="icone vendas"><i class="fa-solid fa-bag-shopping"></i></span>
                </div>
                <h4 style="color:#00796B;">R$ 0</h4>
              </a>

            </div>

            <div class="titulo ps-2">
                <h4 class="text-secondary ps-2">Balanço Anual</h4>
            </div>

            <div>
                <div class="card-lg balance">
                    <div class="left-content">
                        <div class="div-chart">
                            <!-- receita -->
                            <div class="chart">
                                <div class="chart-icon green w-receita" style="height: <?= empty($this->view->totalRent['totalRent']) ? 0 : $this->view->totalRent['totalRent']?>px;">.</div>
                            </div>

                            <!-- despesa -->
                            <div class="chart">
                                <div class="chart-icon red w-despesa" style="height: <?= empty($this->view->totalExpenses['totalExpense']) ? 0 : $this->view->totalExpenses['totalExpense']?>px;">.</div>
                            </div>
                        </div>
                    </div>

                    <div class="right-content">
                        <div class="info-rent">
                            <span>Receitas</span>
                            <span class="text-success">R$ <?= empty($this->view->totalRent['totalRent']) ? '0' : str_replace('.', ',', $this->view->totalRent['totalRent']) ?></span>
                        </div>
                        <div class="info-expense">
                            <span>Despesa</span>
                            <span class="text-danger">R$ <?= empty($this->view->totalExpenses['totalExpense']) ? '0' : str_replace('.', ',', $this->view->totalExpenses['totalExpense']) ?></span>
                        </div>
                        <div class="info-balanco">
                            <span>Balanço</span>
                            <span>R$ <?= str_replace('.', ',', ($this->view->totalRent['totalRent'] - $this->view->totalExpenses['totalExpense'])) ?></span>
                        </div>
                    </div>

                </div>
            </div>
            
            
        </div>

        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        <script src="./js/jQuery.js"></script>
        <script src="./js/main.js"></script>    
        <script src="./js/mes.js"></script>
        <script src="./js/despesa.js"></script>
        <script src="./js/receita.js"></script>
        <script>
            const div = document.getElementById('register')
            document.body.onload = div_close();

            function div_close(){
                if(div){
                    setTimeout(fechar_div, 3000)
                }
            }

            function fechar_div(){
                document.getElementById('register').style.display = 'none'
            }
        </script>
    </body>
</html>

