<?php
    if(!(isset($_SESSION['logged']) && $_SESSION['logged'] === 'LOGGED')){
        header('Location: /?session=timeOut');
    }
?>
<!DOCTYPE html>
<html lang="pt-br">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="./css-bootstrap/bootstrap.min.css">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link rel="stylesheet" href="./fontawesome/css/all.min.css">
        <link rel="shortcut icon" href="./img/coins-solid.svg" type="image/x-icon">
        <link rel="stylesheet" href="./css/style.css">
        <link rel="stylesheet" href="./css/css-sidebar.css">
        <link rel="stylesheet" href="./css/css-cards.css">
        <link rel="stylesheet" href="./css/css-menu.css">
        <link rel="stylesheet" href="./css/css-checkbox.css">
        <link rel="stylesheet" href="./css/modal.css">
        <link rel="stylesheet" href="./css/receita.css">
        <link rel="stylesheet" href="./css/despesa.css">
        <link rel="stylesheet" href="./css/seletores.css">
        <link rel="stylesheet" href="./css/media-query.css">
        <link rel="stylesheet" href="./css/mes.css">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Maven+Pro:wght@400;500&display=swap" rel="stylesheet"> 
        <title>Despesas</title>
    </head>
    <body>
        <!-- modal receitas -->
        <div id="modal-receita" class="modal d-none">
            <div class="modal-body">
                <div class="modal-content modal-receita">
                    <div class="mh">
                        <h4 class="d-inline">Nova Receita</h4>
                        <span id="fechar" class="close fa-regular fa-x" onclick="fechar('modal-receita')"></span>
                    </div>

                    <form action="/novaReceita">
                        <!-- valor -->
                        <div class="input-group">
                            <i class="fa-solid fa-calculator"></i>
                            <input type="text" name="valor" id="valor-receita" class="form-control" placeholder="R$">
                        </div>

                        <!-- rent paga -->
                        <div>
                            <div class="row d-flex receita-check">
                                <div class="col-6 align-self-end">
                                    <i class="fa-regular fa-circle-check check-icon"></i>
                                    <label id="text-switch-receita" for="switch-receita" class="text-switch">Liquidado</label>
                                </div>
                                <div class="col-6 d-flex justify-content-end">
                                    <input type="checkbox" id="switch-receita" class="checkbox" value="liquidado" name="isPaid" checked=true>
                                    <label for="switch-receita" class="toggle"></label>
                                </div>
                            </div>
                        </div>

                        <!-- data -->
                        <div class="mt-4 input-group">
                            <i class="fa-solid fa-calendar-days"></i>
                            <input id="dt-receita" type="date" name="data" class="form-control">
                        </div>

                        <!-- pagador -->
                        <div class="mt-4 input-group">
                            <i class="fa-solid fa-receipt"></i>
                            <input type="text" name="payer" id="pagador-receita" class="form-control" placeholder="Pagador">
                        </div>

                        <!-- categoria -->
                        <div class="select-categoria-receita mt-4">

                            <div class="container-box">

                                <div id="categoria-receita" class="container-options">

                                    <div class="option r">
                                        <input type="radio" name="categoria" class="radio" id="venda-mercadoria" value="venda-mercadoria">
                                        <label for="venda-mercadoria">Venda de Mercadoria</label>
                                    </div>

                                    <div class="option r">
                                        <input type="radio" name="categoria" class="radio" id="servico" value="serviço">
                                        <label for="servico">Serviço</label>
                                    </div>

                                    <div class="option r">
                                        <input type="radio" name="categoria" class="radio" id="matriz" value="matriz">
                                        <label for="matriz">Matriz</label>
                                    </div>
                                </div>
                                <div id="cat-selector-receita" class="selected-option">
                                    <i class="fa-solid fa-flag"></i>
                                    <span id="text-receita">Categorias</span>
                                </div>
                            </div>
                        </div>

                        <!-- carteira -->
                        <div class="div-carteira-receita mt-4">
                            <div class="container-box">
                                <div id="carteira-receita" class="container-options">
                                    <div class="option w">
                                        <input type="radio" name="carteira-receita" id="empresa-receita" class="radio" value="empresa">
                                        <label for="empresa-receita">Empresa</label>
                                    </div>

                                    <div class="option w">
                                        <input type="radio" name="carteira-receita" id="pessoal-receita" class="radio" value="pessoal">
                                        <label for="pessoal-receita">Pessoal</label>
                                    </div>
                                </div>

                                <div id="wallet-selector-receita" class="selected-option">
                                    <i class="fa-solid fa-building-columns"></i>
                                    <span id="wallet-text">Carteira</span>
                                </div>
                            </div>
                        </div>

                        <!-- botão submit -->
                        <div class="submit receita mt-4">
                            <button type="submit">Salvar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- modal despesa-->
        <div id="modal" class="modal d-none">
            <div class="modal-body">
                <div class="modal-content modal-despesa">
                    <div class="mh">
                        <h4>Nova Despesa</h4>
                        <span class="close fa-regular fa-x" onclick="fechar('modal')"></span>
                    </div>
                    <form action="/novaDespesa">
                        <!-- valor -->
                        <div class="input-group">
                            <i class="fa-solid fa-calculator"></i>
                            <input type="text" name="valor" id="valor" class="form-control despesa-valor" placeholder="R$">
                        </div>

                        <!-- despesa paga -->
                        <div>
                            <div class="row d-flex">
                                <div class="col-6 align-self-end">
                                    <i class="fa-regular fa-circle-check check-icon"></i>
                                    <label id="text-switch" for="switch" class="text-switch">Foi Paga</label>
                                </div>
                                <div class="col-6 d-flex justify-content-end">
                                    <input type="checkbox" id="switch" class="checkbox" value="pago" name="isPaid" checked=true>                        
                                    <label for="switch" class="toggle"></label>
                                </div>
                            </div>
                        </div>

                        <!-- data -->
                        <div class="mt-4 input-group">
                            <i class="fa-solid fa-calendar-days"></i>
                            <input id="dt" type="date" name="data" class="form-control"> 
                        </div>

                        <!-- beneficiario -->
                        <div class="mt-4 input-group">
                            <i class="fa-solid fa-receipt"></i>
                            <input type="text" name="bene" id="bene" class="form-control" placeholder="Beneficiário">
                        </div>

                        <!-- categoria -->
                        <div class="select-categoria mt-4">
                
                            <div class="container-box">

                                <div id="categoria" class="container-options">

                                    <div class="option waD">
                                        <input type="radio" name="categoria" class="radio" id="compra-mercadoria" value="compra-mercadoria">
                                        <label for="compra-mercadoria">Compra de Mercadoria</label>
                                    </div>

                                    <div class="option waD">
                                        <input type="radio" name="categoria" class="radio" id="conta" value="conta">
                                        <label for="conta">Contas</label>
                                    </div>

                                    <div class="option waD">
                                        <input type="radio" name="categoria" class="radio" id="imposto" value="imposto">
                                        <label for="imposto">Impostos</label>
                                    </div>

                                    <div class="option waD">
                                        <input type="radio" name="categoria" class="radio" id="alimentacao" value="alimentacao">
                                        <label for="alimentacao">Alimentação</label>
                                    </div>

                                    <div class="option waD">
                                        <input type="radio" name="categoria" class="radio" id="transporte" value="transporte">
                                        <label for="transporte">Transporte</label>
                                    </div>                                
                                </div> 
                                <div id="categoria-select" class="selected-option ">
                                    <i class="fa-solid fa-flag"></i>
                                    <span id="cat-text">Categorias</span>
                                </div>
                            </div>  
                        </div>
                        
                        <!-- carteira -->
                        <div class="div-carteira mt-4">
                            <div class="container-box">
                                <div id="carteira" class="container-options" >
                                    <div class="option wd">
                                        <input type="radio" name="carteira" id="empresa" class="radio" value="empresa">
                                        <label for="empresa">Empresa</label>
                                    </div>

                                    <div class="option wd">
                                        <input type="radio" name="carteira" id="pessoal" class="radio" value="pessoal">
                                        <label for="pessoal">Pessoal</label>
                                    </div>
                                </div>

                                <div id="wdSelector" class="selected-option">
                                    <i class="fa-solid fa-building-columns"></i>
                                    <span id="wdText">Carteira</span>
                                </div>
                            </div>
                        </div>

                        <!-- botão submit -->
                        <div class="submit mt-4">
                            <button type="submit">Salvar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- modal expense edit-->
        <div id="modal-edit-despesa" class="modal d-none">
            <div class="modal-body">
                <div class="modal-content modal-despesa">
                    <div class="mh">
                        <h4>Nova Despesa</h4>
                        <span class="close fa-regular fa-x" onclick="fechar('modal-edit-despesa')"></span>
                    </div>
                    <form id="t">
                        <!-- valor -->
                        <div class="input-group">
                            <i class="fa-solid fa-calculator"></i>
                            <input type="text" name="valor" id="valor-edit" class="form-control despesa-valor" placeholder="R$">
                        </div>

                        <!-- despesa paga -->
                        <div>
                            <div class="row d-flex">
                                <div class="col-6 align-self-end">
                                    <i class="fa-regular fa-circle-check check-icon"></i>
                                    <label id="text-switch-edit" for="switch-edit" class="text-switch">Foi Paga</label>
                                </div>
                                <div class="col-6 d-flex justify-content-end">
                                    <input type="checkbox" id="switch-edit" class="checkbox" value="pago" name="isPaid" checked=true>                        
                                    <label id="toggle" for="switch-edit" class="toggle"></label>
                                </div>
                            </div>
                        </div>

                        <!-- data -->
                        <div class="mt-4 input-group">
                            <i class="fa-solid fa-calendar-days"></i>
                            <input id="dt-edit" type="date" name="data" class="form-control"> 
                        </div>

                        <!-- beneficiario -->
                        <div class="mt-4 input-group">
                            <i class="fa-solid fa-receipt"></i>
                            <input type="text" name="bene" id="bene-edit" class="form-control" placeholder="Beneficiário">
                        </div>

                        <!-- categoria -->
                        <div class="select-categoria mt-4">
                
                            <div class="container-box">

                                <div id="categoria-edit" class="container-options cat-edit">

                                    <div class="option edit">
                                        <input type="radio" name="categoria" class="radio" id="compra-mercadoria-edit" value="compra-mercadoria">
                                        <label for="compra-mercadoria-edit">Compra de Mercadoria</label>
                                    </div>

                                    <div class="option edit">
                                        <input type="radio" name="categoria" class="radio" id="conta-edit" value="conta">
                                        <label for="conta-edit">Contas</label>
                                    </div>

                                    <div class="option edit">
                                        <input type="radio" name="categoria" class="radio" id="imposto-edit" value="imposto">
                                        <label for="imposto-edit">Impostos</label>
                                    </div>

                                    <div class="option edit">
                                        <input type="radio" name="categoria" class="radio" id="alimentacao-edit" value="alimentacao">
                                        <label for="alimentacao-edit">Alimentação</label>
                                    </div>

                                    <div class="option edit">
                                        <input type="radio" name="categoria" class="radio" id="transporte-edit" value="transporte">
                                        <label for="transporte-edit">Transporte</label>
                                    </div>                                
                                </div> 
                                <div id="selected-cat-edit" class="selected-option">
                                    <i class="fa-solid fa-flag"></i>
                                    <span id="text-edit" class="text-capitalize">Categorias</span>
                                </div>
                            </div>  
                        </div>
                        
                        <!-- carteira -->
                        <div class="div-carteira mt-4">
                            <div class="container-box">
                                <div id="carteira-edit" class="container-options edit-wallet        ">
                                    <div class="option wde">
                                        <input type="radio" name="carteira" id="empresa-edit" class="radio" value="empresa">
                                        <label for="empresa-edit">Empresa</label>
                                    </div>

                                    <div class="option wde">
                                        <input type="radio" name="carteira" id="pessoal-edit" class="radio" value="pessoal">
                                        <label for="pessoal-edit">Pessoal</label>
                                    </div>
                                </div>

                                <div id="wallet-edit" class="selected-option">
                                    <i class="fa-solid fa-building-columns"></i>
                                    <span id="wa-edit" class="text-capitalize">Carteira</span>
                                </div>
                            </div>
                        </div>

                        <!-- botão submit -->
                        <div class="submit mt-4">
                            <button id="btn-save-edit" type="button">Salvar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

        <!-- barra lateral -->
        <div id="sidebar">
            <div class="sibebar-logo">
                <a href="/"><img src="./img/img.png" width="80" alt=""></a>
            </div>

            <div class="sidebar-btn-add">
                <div id="btn-add">
                    <button id="btn" class="btn-sidebar">
                        <i id="btn-icon" class="fa-solid fa-plus"></i>
                    </button>

                    <ul id="menu" class="d-none">
                        <li>
                            <a onclick="modal('modal')" class="cl">
                                <i class="fa-solid fa-arrow-trend-down dp"></i>
                                Despesa
                            </a>
                        </li>
                        <li>
                            <a onclick="modal('modal-receita')" class="cl">
                                <i class="fa-solid fa-arrow-trend-up rt"></i>
                                Receita
                            </a>
                        </li>
                        <li><a href="">
                            <i class="fa-solid fa-bag-shopping vd"></i>
                            Venda
                        </a></li>
                    </ul>
                </div>
            </div>

            <div class="sidebar-menu">
                <ul>
                    <li class="margin-t">
                        <a href="/"><img src="./img/home.png" width="35" alt=""></a>
                    </li>
                    <li class="margin-t active">
                        <a href="#"><img src="./img/lista.png" width="33" alt=""></i></a>
                    </li>
                </ul>

            </div>
        </div>

        <!-- conteudo principal -->
        <div id="content" class="content">
            <div class="topo" id="expense-pg">
                <div id="usuario" class="user">
                    <span class="user"><img class="user-image" src="<?= isset($_SESSION['image']) ? $_SESSION['image'] : '' ?>" alt=""></span>
                    <span class="user-name"><?= isset($_SESSION['user']) ? $_SESSION['user'] : '' ?></span>
                    <span class="angle"><i class="fa-solid fa-angle-down"></i></span>
                </div>

                <div id="drop-user" class="menu-user">
                    <ul>
                        <li><a href=""><i class="fa-regular fa-circle-user"></i>Meu Perfil</a></li>
                        <li><a href=""><i class="fa-solid fa-gear"></i>Configurações</a></li>
                        <li><a href="/logout"><i class="fa-solid fa-arrow-right-from-bracket"></i>Sair</a></li>
                    </ul>
                </div>
            </div>
            <!-- barra de opções -->
            <div class="interaction">
                <div onclick="show('drop')" class="left-btn">
                    <span class="btn-icon"><i class="fa-solid fa-angle-down"></i></span>
                    <span>Despesa</span>
                </div>
                <div id="drop" class="drop-menu d-none">
                    <div class="drop-content">
                        <ul>
                            <li class="mt-2">
                                <a href="/despesa">
                                    <i class="fa-solid fa-circle text-red"></i>
                                    Despesas
                                </a>
                            </li>
                            <li>
                                <a href="/receitas">
                                    <i class="fa-solid fa-circle text-green"></i>
                                    Receitas
                                </a>
                            </li>
                            <li>
                                <a href="">
                                    <i class="fa-solid fa-circle text-vendas"></i>
                                    Vendas
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="options-right">
                    <div class="new-expense" onclick="modal('modal')">
                        <span class="icon"><i class="fa-solid fa-plus"></i></span>
                        <span>nova despesa</span>
                    </div>
                    <div class="search">
                        <span><i class="fa-solid fa-magnifying-glass"></i></span>
                    </div>
                    <div class="filter">
                        <span><i class="fa-solid fa-filter"></i></span>
                    </div>
                </div>
            </div>
            <!-- cartoes de valores -->
            <div class="linha">
                <div class="cartao desepesas">
                    <span class="text-card">Despesas Pendentes<img src="./img/angle.png" width="25" alt=""></span>
                    <div class="icone-circle">
                        <span class="icone saldo"><i class="fa-solid fa-arrow-up"></i></span>
                    </div>
                    <h4>R$ <?= empty($this->view->expensesNp['noPaid']) ? '0,00' : str_replace('.', ',', $this->view->expensesNp['noPaid']) ?></h4>
                </div>

                <div class="cartao desepesas">
                    <span class="text-card">Despesas Pagas<img src="./img/angle.png" width="25" alt=""></span>
                    <div class="icone-circle">
                        <span class="icone saldo"><i class="fa-solid fa-arrow-down"></i></span>
                    </div>
                    <h4>R$ <?= empty($this->view->expensesPaid['paid']) ? '0,00' : str_replace('.', ',', $this->view->expensesPaid['paid']) ?></h4>
                </div>

                <div class="cartao desepesas">
                    <span class="text-card">Total<img src="./img/angle.png" width="25" alt=""></span>
                    <div class="icone-circle c-saldo">
                        <span class="icone saldo"><i class="fa-solid fa-scale-balanced balence"></i></span>
                    </div>
                    <h4>R$ <?= empty($this->view->totalExpenses['total']) ? '0,00' : str_replace('.', ',', $this->view->totalExpenses['total']) ?></h4>
                </div>
            </div>
            <!-- tabela -->
            <div class="card-lg tabela">
                <div>
                    <div class="calendar-transation">
                        <div class="view despesa-list">
                            <span><i class="fa-solid fa-angle-left"></i></span>
                            <span class="text-month"><span class="month">maio</span> <span class="year">2022</span></span>
                            <span><i class="fa-solid fa-angle-right"></i></span>
                        </div>
                    </div>
                    <table>
                        <thead class="thead">
                            <tr>
                                <th scope="col">Situação</th>
                                <th scope="col">Data</th>
                                <th scope="col">Beneficiário</th>
                                <th scope="col">Categoria</th>
                                <th scope="col">Conta</th>
                                <th scope="col">Valor</th>
                                <th scope="col">Ações</th>
                            </tr>
                        </thead>
                        <tbody id="tbody-data">                            
                        </tbody>                    
                    </table>
                </div>
                <div class="table-footer">
                    <span>Linhas por página:</span>
                    <div id="sLPP" class="lPP">
                        <span class="ql" id="nOL"></span>
                        <i class="fa-solid fa-sort-down"></i>
                    </div>
                    <div class="toggles">
                        <i onclick="getDataExpense()" class="fa-solid fa-angles-left"></i>
                        <i onclick="previusPage(<?= $this->view->totalDeDespesas['total'] ?>)" class="fa-solid fa-chevron-left"></i>
                        <i onclick="nextPage(<?= $this->view->totalDeDespesas['total'] ?>)" class="fa-solid fa-chevron-right"></i>
                        <i onclick="lastPage(<?= $this->view->totalDeDespesas['total'] ?>)" class="fa-solid fa-angles-right"></i>
                    </div>
                    <div id="lPPM">
                        <div class="optlpp">
                            <input type="radio" name="lpp" id="5" class="radio" value="5">
                            <label for="5">5</label>
                        </div>   
                        <div class="optlpp">
                            <input type="radio" name="lpp" id="10" class="radio" value="10">
                            <label for="10">10</label>
                        </div> 
                        <div class="optlpp">
                            <input type="radio" name="lpp" id="25" class="radio" value="25">
                            <label for="25">25</label>
                        </div> 
                        <div class="optlpp">
                            <input type="radio" name="lpp" id="50" class="radio" value="50">
                            <label for="50">50</label>
                        </div>             
                    </div>
                </div>
            </div>
        </div>

        <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
        <script src="./js-bootstrap/bootstrap.bundle.min.js"></script>
        <script src="./js/main.js"></script>
        <script src="./js/despesa.js"></script>
        <script src="./js/receita.js"></script>
        <script src="./js/edit.js"></script>
        <script src="./js/interaction-table.js"></script>
        <script src="./js/pagination.js"></script>
    </body>
</html>