<?php foreach($this->view->dados as $key => $despesa){ ?>
    <tr id="expense_<?= $despesa['id'] ?>">
        <td>
            <?php if($despesa['isPaid'] == 'pago'){ ?>
                <span style="background-color: #4CAF50;" class="status"><i class="fa-solid fa-check paid"></i></span>
            <?php }else if($despesa['isPaid'] == 'n/p'){ ?>
                <span class="status"><i class="fa-solid fa-exclamation np"></i></span>
            <?php } ?>
        </td>
        <td><?= substr($despesa['date_expense'], 8) . '/' . substr($despesa['date_expense'], 5, 2) . '/' . substr($despesa['date_expense'], 0,4) ?></td>
        <td><?= $despesa['recipient'] ?></td>
        <td><?=$despesa['category']?></td>
        <td><?=$despesa['wallet']?></td>
        <td class="fw-light text-danger"><?='R$ ' . str_replace('.', ',', $despesa['value_expense'])?></td>
        <td>
            <div class="table-box">
                <?php if($despesa['isPaid'] == 'n/p'){ ?>
                    <span onclick="pay(<?= $despesa['id'] ?>)" class="action pe-3"><abbr title="Pagar"><i class="fa-regular fa-circle-check"></i></abbr></span>
                <?php } ?>
                <span onclick="edit(<?= $despesa['id'] ?>)" class="action pe-3"><abbr title="Editar"><i class="fa-solid fa-pencil"></i></abbr></span>
                <span onclick="exclude(<?= $despesa['id'] ?>)" class="action"><abbr title="Excluir"><i class="fa-solid fa-trash-can"></i></abbr></span>
            </div>
        </td>
    </tr>
<?php } ?>